version: '3.8'

services:
  haproxy:  
    image: haproxy:2.8
    container_name: haproxy
    ports:
      - "80:80"
      - "2000:8080"  # For stats page
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - app-network
    depends_on:
      - nginx1
      - nginx2

  nginx1:
    image: nginx:alpine
    container_name: nginx1
    volumes:
      - ./nginx1.conf:/etc/nginx/conf.d/default.conf
      - ./html1:/usr/share/nginx/html
    networks:
      - app-network

  nginx2:
    image: nginx:alpine
    container_name: nginx2
    volumes:
      - ./nginx2.conf:/etc/nginx/conf.d/default.conf
      - ./html2:/usr/share/nginx/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
