name: Release Please
on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: "simple" 
          token: ${{ secrets.GH_TOKEN }}
          - name: Release Please
          changelog-types: '[{"type":"feat","section":"Features"},{"type":"fix","section":"Fixes"}]'
          command: "github-release"  # Force release creation
        env:
          DEBUG: "release-please"  # Enable verbose logging
