name: Release Please
on:
  pull_request:
    branches:
      - main
    types: [closed]  # Only trigger when a PR is closed (merged or not)

jobs:
  release-please:
    # Only run if the PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Release Please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: "simple"
          token: ${{ secrets.GH_TOKEN }}
